//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TablichnayaCHast
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Накладная.
    /// </summary>
    // *** Start programmer edit section *** (Накладная CustomAttributes)

    // *** End programmer edit section *** (Накладная CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НакладнаяE", new string[] {
            "ТипНакл as \'Тип накл\'"})]
    [View("НакладнаяL", new string[] {
            "ТипНакл as \'Тип накл\'"})]
    public class Накладная : ICSSoft.STORMNET.DataObject
    {
        
        private string fТипНакл;
        
        private IIS.TablichnayaCHast.DetailArrayOfОтветственный fОтветственный;
        
        // *** Start programmer edit section *** (Накладная CustomMembers)

        // *** End programmer edit section *** (Накладная CustomMembers)

        
        /// <summary>
        /// ТипНакл.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.ТипНакл CustomAttributes)

        // *** End programmer edit section *** (Накладная.ТипНакл CustomAttributes)
        [StrLen(255)]
        public virtual string ТипНакл
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.ТипНакл Get start)

                // *** End programmer edit section *** (Накладная.ТипНакл Get start)
                string result = this.fТипНакл;
                // *** Start programmer edit section *** (Накладная.ТипНакл Get end)

                // *** End programmer edit section *** (Накладная.ТипНакл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.ТипНакл Set start)

                // *** End programmer edit section *** (Накладная.ТипНакл Set start)
                this.fТипНакл = value;
                // *** Start programmer edit section *** (Накладная.ТипНакл Set end)

                // *** End programmer edit section *** (Накладная.ТипНакл Set end)
            }
        }
        
        /// <summary>
        /// Накладная.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Ответственный CustomAttributes)

        // *** End programmer edit section *** (Накладная.Ответственный CustomAttributes)
        public virtual IIS.TablichnayaCHast.DetailArrayOfОтветственный Ответственный
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Ответственный Get start)

                // *** End programmer edit section *** (Накладная.Ответственный Get start)
                if ((this.fОтветственный == null))
                {
                    this.fОтветственный = new IIS.TablichnayaCHast.DetailArrayOfОтветственный(this);
                }
                IIS.TablichnayaCHast.DetailArrayOfОтветственный result = this.fОтветственный;
                // *** Start programmer edit section *** (Накладная.Ответственный Get end)

                // *** End programmer edit section *** (Накладная.Ответственный Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Ответственный Set start)

                // *** End programmer edit section *** (Накладная.Ответственный Set start)
                this.fОтветственный = value;
                // *** Start programmer edit section *** (Накладная.Ответственный Set end)

                // *** End programmer edit section *** (Накладная.Ответственный Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НакладнаяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НакладнаяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НакладнаяE", typeof(IIS.TablichnayaCHast.Накладная));
                }
            }
            
            /// <summary>
            /// "НакладнаяL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НакладнаяL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НакладнаяL", typeof(IIS.TablichnayaCHast.Накладная));
                }
            }
        }
    }
}
