//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TablichnayaCHast
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ответственный.
    /// </summary>
    // *** Start programmer edit section *** (Ответственный CustomAttributes)

    // *** End programmer edit section *** (Ответственный CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтветственныйE", new string[] {
            "Фамилия as \'Фамилия\'"})]
    [View("ОтветственныйL", new string[] {
            "Фамилия as \'Фамилия\'"})]
    public class Ответственный : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private string fИмя;
        
        private IIS.TablichnayaCHast.Накладная fНакладная;
        
        // *** Start programmer edit section *** (Ответственный CustomMembers)

        // *** End programmer edit section *** (Ответственный CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Ответственный.Имя CustomAttributes)

        // *** End programmer edit section *** (Ответственный.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Ответственный.Имя Get start)

                // *** End programmer edit section *** (Ответственный.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Ответственный.Имя Get end)

                // *** End programmer edit section *** (Ответственный.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ответственный.Имя Set start)

                // *** End programmer edit section *** (Ответственный.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Ответственный.Имя Set end)

                // *** End programmer edit section *** (Ответственный.Имя Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Ответственный.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Ответственный.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Ответственный.Фамилия Get start)

                // *** End programmer edit section *** (Ответственный.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Ответственный.Фамилия Get end)

                // *** End programmer edit section *** (Ответственный.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ответственный.Фамилия Set start)

                // *** End programmer edit section *** (Ответственный.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Ответственный.Фамилия Set end)

                // *** End programmer edit section *** (Ответственный.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.TablichnayaCHast.Накладная.
        /// </summary>
        // *** Start programmer edit section *** (Ответственный.Накладная CustomAttributes)

        // *** End programmer edit section *** (Ответственный.Накладная CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Накладная"})]
        public virtual IIS.TablichnayaCHast.Накладная Накладная
        {
            get
            {
                // *** Start programmer edit section *** (Ответственный.Накладная Get start)

                // *** End programmer edit section *** (Ответственный.Накладная Get start)
                IIS.TablichnayaCHast.Накладная result = this.fНакладная;
                // *** Start programmer edit section *** (Ответственный.Накладная Get end)

                // *** End programmer edit section *** (Ответственный.Накладная Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ответственный.Накладная Set start)

                // *** End programmer edit section *** (Ответственный.Накладная Set start)
                this.fНакладная = value;
                // *** Start programmer edit section *** (Ответственный.Накладная Set end)

                // *** End programmer edit section *** (Ответственный.Накладная Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтветственныйE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтветственныйE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтветственныйE", typeof(IIS.TablichnayaCHast.Ответственный));
                }
            }
            
            /// <summary>
            /// "ОтветственныйL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтветственныйL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтветственныйL", typeof(IIS.TablichnayaCHast.Ответственный));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Ответственный.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОтветственный CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОтветственный CustomAttributes)
    public class DetailArrayOfОтветственный : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.TablichnayaCHast.DetailArrayOfОтветственный members)

        // *** End programmer edit section *** (IIS.TablichnayaCHast.DetailArrayOfОтветственный members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Ответственный by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Ответственный.
        /// </summary>
        public DetailArrayOfОтветственный(IIS.TablichnayaCHast.Накладная fНакладная) : 
                base(typeof(Ответственный), ((ICSSoft.STORMNET.DataObject)(fНакладная)))
        {
        }
        
        public IIS.TablichnayaCHast.Ответственный this[int index]
        {
            get
            {
                return ((IIS.TablichnayaCHast.Ответственный)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.TablichnayaCHast.Ответственный dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
